Test

diff --git a/.github/workflows/appsignals-e2e-test.yml b/.github/workflows/appsignals-e2e-test.yml
--- a/.github/workflows/appsignals-e2e-test.yml
+++ b/.github/workflows/appsignals-e2e-test.yml
@@ -26,7 +26,7 @@ env:
   SAMPLE_APP_REMOTE_SERVICE_IMAGE: ${{ secrets.APP_SIGNALS_E2E_SAMPLE_APP_REMOTE_SVC_IMG }}
   METRIC_NAMESPACE: AppSignals
   LOG_GROUP: /aws/appsignals/eks
-  ECR_OPERATOR_STAGING_IMAGE: 506463145083.dkr.ecr.us-west-2.amazonaws.com/cwagent-operator-pre-release:latest
+  ECR_OPERATOR_STAGING_IMAGE: ${{ secrets.ECR_OPERATOR_STAGING_IMAGE }}
 
 jobs:
   appsignals-e2e-test:
@@ -52,7 +52,7 @@ jobs:
           sparse-checkout-cone-mode: false
 
       - name: Generate testing id
-        run: echo TESTING_ID="us-east-1-8180234754-70" >> $GITHUB_ENV
+        run: echo TESTING_ID="${{ env.AWS_DEFAULT_REGION }}-${{ github.run_id }}-${{ github.run_number }}" >> $GITHUB_ENV
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -123,144 +123,144 @@ jobs:
         run: |
           echo "OLD_CW_AGENT_OPERATOR_IMAGE"=$(kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=amazon-cloudwatch-observability -o json | \
           jq '.items[0].status.containerStatuses[0].image') >> $GITHUB_ENV
-#
-#      - name: Patch the CloudWatch Agent Operator image and restart CloudWatch pods
-#        run: |
-#          kubectl patch deploy -n amazon-cloudwatch amazon-cloudwatch-observability-controller-manager --type='json' -p '[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "${{ env.ECR_OPERATOR_STAGING_IMAGE }}"}]'
-#          kubectl delete pods --all -n amazon-cloudwatch
-#          kubectl wait --for=condition=Ready pod --all -n amazon-cloudwatch
-#
-#      # Application pods need to be restarted for the
-#      # app signals instrumentation to take effect
-#      - name: Restart the app pods
-#        run: kubectl delete pods --all -n ${{ env.SAMPLE_APP_NAMESPACE }}
-#
-#      - name: Wait for sample app pods to come up
-#        run: |
-#          kubectl wait --for=condition=Ready pod --all -n ${{ env.SAMPLE_APP_NAMESPACE }} \
-#
-#      - name: Get remote service deployment name and IP
-#        run: |
-#          echo "REMOTE_SERVICE_DEPLOYMENT_NAME=$(kubectl get deployments -n ${{ env.SAMPLE_APP_NAMESPACE }} --selector=app=remote-app -o jsonpath='{.items[0].metadata.name}')" >> $GITHUB_ENV
-#          echo "REMOTE_SERVICE_POD_IP=$(kubectl get pods -n ${{ env.SAMPLE_APP_NAMESPACE }} --selector=app=remote-app -o jsonpath='{.items[0].status.podIP}')" >> $GITHUB_ENV
-#
-#      - name: Log pod ADOT image ID
-#        run: |
-#          kubectl get pods -n ${{ env.SAMPLE_APP_NAMESPACE }} --output json | \
-#          jq '.items[0].status.initContainerStatuses[0].imageID'
-#
-#      - name: Log pod CWAgent image ID
-#        run: |
-#          kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=cloudwatch-agent -o json | \
-#          jq '.items[0].status.containerStatuses[0].imageID'
-#
-#      - name: Log pod Fluent Bit image ID
-#        run: |
-#          kubectl get pods -n amazon-cloudwatch -l k8s-app=fluent-bit -o json | \
-#          jq '.items[0].status.containerStatuses[0].imageID'
-#
-#      - name: Log pod CWAgent Operator image ID and save image to the environment
-#        run: |
-#          kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=amazon-cloudwatch-observability -o json | \
-#          jq '.items[0].status.containerStatuses[0].imageID'
-#
-#          echo "NEW_CW_AGENT_OPERATOR_IMAGE"=$(kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=amazon-cloudwatch-observability -o json | \
-#          jq '.items[0].status.containerStatuses[0].image') >> $GITHUB_ENV
-#
-#      - name: Check if CW Agent Operator image has changed
-#        run: |
-#          if [ ${{ env.OLD_CW_AGENT_OPERATOR_IMAGE }} = ${{ env.NEW_CW_AGENT_OPERATOR_IMAGE }} ]; then
-#            echo "Operator image did not change"
-#            exit 1
-#          fi
-#
-#      - name: Get the sample app endpoint
-#        run: |
-#          echo "APP_ENDPOINT=$(terraform output sample_app_endpoint)" >> $GITHUB_ENV
-#        working-directory: terraform/eks
-#
-#      - name: Wait for app endpoint to come online
-#        id: endpoint-check
-#        run: |
-#          attempt_counter=0
-#          max_attempts=30
-#          until $(curl --output /dev/null --silent --head --fail http://${{ env.APP_ENDPOINT }}); do
-#            if [ ${attempt_counter} -eq ${max_attempts} ];then
-#              echo "Max attempts reached"
-#              exit 1
-#            fi
-#
-#            printf '.'
-#            attempt_counter=$(($attempt_counter+1))
-#            sleep 10
-#          done
-#
-#      # This steps increases the speed of the validation by creating the telemetry data in advance
-#      - name: Call all test APIs
-#        continue-on-error: true
-#        run: |
-#          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/outgoing-http-call/
-#          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/aws-sdk-call/
-#          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/remote-service?ip=${{ env.REMOTE_SERVICE_POD_IP }}/
-#          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/client-call/
-#
-#      - name: Build Gradle
-#        run: ./gradlew
-#
-#      # Validation for app signals telemetry data
-#      - name: Call endpoint and validate generated EMF logs
-#        id: log-validation
-#        if: steps.endpoint-check.outcome == 'success' && !cancelled()
-#        run: ./gradlew validator:run --args='-c eks/log-validation.yml
-#          --testing-id ${{ env.TESTING_ID }}
-#          --endpoint http://${{ env.APP_ENDPOINT }}
-#          --region ${{ env.AWS_DEFAULT_REGION }}
-#          --account-id ${{ env.TEST_ACCOUNT }}
-#          --metric-namespace ${{ env.METRIC_NAMESPACE }}
-#          --log-group ${{ env.LOG_GROUP }}
-#          --app-namespace ${{ env.SAMPLE_APP_NAMESPACE }}
-#          --platform-info ${{ inputs.test-cluster-name }}
-#          --service-name sample-application-${{ env.TESTING_ID }}
-#          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_DEPLOYMENT_NAME }}
-#          --request-body ip=${{ env.REMOTE_SERVICE_POD_IP }}
-#          --rollup'
-#
-#      - name: Call endpoints and validate generated metrics
-#        id: metric-validation
-#        if: (success() || steps.log-validation.outcome == 'failure') && !cancelled()
-#        run: ./gradlew validator:run --args='-c eks/metric-validation.yml
-#          --testing-id ${{ env.TESTING_ID }}
-#          --endpoint http://${{ env.APP_ENDPOINT }}
-#          --region ${{ env.AWS_DEFAULT_REGION }}
-#          --account-id ${{ env.TEST_ACCOUNT }}
-#          --metric-namespace ${{ env.METRIC_NAMESPACE }}
-#          --log-group ${{ env.LOG_GROUP }}
-#          --app-namespace ${{ env.SAMPLE_APP_NAMESPACE }}
-#          --platform-info ${{ inputs.test-cluster-name }}
-#          --service-name sample-application-${{ env.TESTING_ID }}
-#          --remote-service-name sample-remote-application-${{ env.TESTING_ID }}
-#          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_DEPLOYMENT_NAME }}
-#          --request-body ip=${{ env.REMOTE_SERVICE_POD_IP }}
-#          --rollup'
-#
-#      - name: Call endpoints and validate generated traces
-#        id: trace-validation
-#        if: (success() || steps.log-validation.outcome == 'failure' || steps.metric-validation.outcome == 'failure') && !cancelled()
-#        run: ./gradlew validator:run --args='-c eks/trace-validation.yml
-#          --testing-id ${{ env.TESTING_ID }}
-#          --endpoint http://${{ env.APP_ENDPOINT }}
-#          --region ${{ env.AWS_DEFAULT_REGION }}
-#          --account-id ${{ env.TEST_ACCOUNT }}
-#          --metric-namespace ${{ env.METRIC_NAMESPACE }}
-#          --log-group ${{ env.LOG_GROUP }}
-#          --app-namespace ${{ env.SAMPLE_APP_NAMESPACE }}
-#          --platform-info ${{ inputs.test-cluster-name }}
-#          --service-name sample-application-${{ env.TESTING_ID }}
-#          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_DEPLOYMENT_NAME }}
-#          --request-body ip=${{ env.REMOTE_SERVICE_POD_IP }}
-#          --rollup'
-#
-      # Clean up Procedures
+
+      - name: Patch the CloudWatch Agent Operator image and restart CloudWatch pods
+        run: |
+          kubectl patch deploy -n amazon-cloudwatch amazon-cloudwatch-observability-controller-manager --type='json' -p '[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "${{ env.ECR_OPERATOR_STAGING_IMAGE }}"}]'
+          kubectl delete pods --all -n amazon-cloudwatch
+          kubectl wait --for=condition=Ready pod --all -n amazon-cloudwatch
+
+      # Application pods need to be restarted for the
+      # app signals instrumentation to take effect
+      - name: Restart the app pods
+        run: kubectl delete pods --all -n ${{ env.SAMPLE_APP_NAMESPACE }}
+
+      - name: Wait for sample app pods to come up
+        run: |
+          kubectl wait --for=condition=Ready pod --all -n ${{ env.SAMPLE_APP_NAMESPACE }} \
+
+      - name: Get remote service deployment name and IP
+        run: |
+          echo "REMOTE_SERVICE_DEPLOYMENT_NAME=$(kubectl get deployments -n ${{ env.SAMPLE_APP_NAMESPACE }} --selector=app=remote-app -o jsonpath='{.items[0].metadata.name}')" >> $GITHUB_ENV
+          echo "REMOTE_SERVICE_POD_IP=$(kubectl get pods -n ${{ env.SAMPLE_APP_NAMESPACE }} --selector=app=remote-app -o jsonpath='{.items[0].status.podIP}')" >> $GITHUB_ENV
+
+      - name: Log pod ADOT image ID
+        run: |
+          kubectl get pods -n ${{ env.SAMPLE_APP_NAMESPACE }} --output json | \
+          jq '.items[0].status.initContainerStatuses[0].imageID'
+
+      - name: Log pod CWAgent image ID
+        run: |
+          kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=cloudwatch-agent -o json | \
+          jq '.items[0].status.containerStatuses[0].imageID'
+
+      - name: Log pod Fluent Bit image ID
+        run: |
+          kubectl get pods -n amazon-cloudwatch -l k8s-app=fluent-bit -o json | \
+          jq '.items[0].status.containerStatuses[0].imageID'
+
+      - name: Log pod CWAgent Operator image ID and save image to the environment
+        run: |
+          kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=amazon-cloudwatch-observability -o json | \
+          jq '.items[0].status.containerStatuses[0].imageID'
+
+          echo "NEW_CW_AGENT_OPERATOR_IMAGE"=$(kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=amazon-cloudwatch-observability -o json | \
+          jq '.items[0].status.containerStatuses[0].image') >> $GITHUB_ENV
+
+      - name: Check if CW Agent Operator image has changed
+        run: |
+          if [ ${{ env.OLD_CW_AGENT_OPERATOR_IMAGE }} = ${{ env.NEW_CW_AGENT_OPERATOR_IMAGE }} ]; then
+            echo "Operator image did not change"
+            exit 1
+          fi
+
+      - name: Get the sample app endpoint
+        run: |
+          echo "APP_ENDPOINT=$(terraform output sample_app_endpoint)" >> $GITHUB_ENV
+        working-directory: terraform/eks
+
+      - name: Wait for app endpoint to come online
+        id: endpoint-check
+        run: |
+          attempt_counter=0
+          max_attempts=30
+          until $(curl --output /dev/null --silent --head --fail http://${{ env.APP_ENDPOINT }}); do
+            if [ ${attempt_counter} -eq ${max_attempts} ];then
+              echo "Max attempts reached"
+              exit 1
+            fi
+
+            printf '.'
+            attempt_counter=$(($attempt_counter+1))
+            sleep 10
+          done
+
+      # This steps increases the speed of the validation by creating the telemetry data in advance
+      - name: Call all test APIs
+        continue-on-error: true
+        run: |
+          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/outgoing-http-call/
+          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/aws-sdk-call/
+          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/remote-service?ip=${{ env.REMOTE_SERVICE_POD_IP }}/
+          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/client-call/
+
+      - name: Build Gradle
+        run: ./gradlew
+
+      # Validation for app signals telemetry data
+      - name: Call endpoint and validate generated EMF logs
+        id: log-validation
+        if: steps.endpoint-check.outcome == 'success' && !cancelled()
+        run: ./gradlew validator:run --args='-c eks/log-validation.yml
+          --testing-id ${{ env.TESTING_ID }}
+          --endpoint http://${{ env.APP_ENDPOINT }}
+          --region ${{ env.AWS_DEFAULT_REGION }}
+          --account-id ${{ env.TEST_ACCOUNT }}
+          --metric-namespace ${{ env.METRIC_NAMESPACE }}
+          --log-group ${{ env.LOG_GROUP }}
+          --app-namespace ${{ env.SAMPLE_APP_NAMESPACE }}
+          --platform-info ${{ inputs.test-cluster-name }}
+          --service-name sample-application-${{ env.TESTING_ID }}
+          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_DEPLOYMENT_NAME }}
+          --request-body ip=${{ env.REMOTE_SERVICE_POD_IP }}
+          --rollup'
+
+      - name: Call endpoints and validate generated metrics
+        id: metric-validation
+        if: (success() || steps.log-validation.outcome == 'failure') && !cancelled()
+        run: ./gradlew validator:run --args='-c eks/metric-validation.yml
+          --testing-id ${{ env.TESTING_ID }}
+          --endpoint http://${{ env.APP_ENDPOINT }}
+          --region ${{ env.AWS_DEFAULT_REGION }}
+          --account-id ${{ env.TEST_ACCOUNT }}
+          --metric-namespace ${{ env.METRIC_NAMESPACE }}
+          --log-group ${{ env.LOG_GROUP }}
+          --app-namespace ${{ env.SAMPLE_APP_NAMESPACE }}
+          --platform-info ${{ inputs.test-cluster-name }}
+          --service-name sample-application-${{ env.TESTING_ID }}
+          --remote-service-name sample-remote-application-${{ env.TESTING_ID }}
+          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_DEPLOYMENT_NAME }}
+          --request-body ip=${{ env.REMOTE_SERVICE_POD_IP }}
+          --rollup'
+
+      - name: Call endpoints and validate generated traces
+        id: trace-validation
+        if: (success() || steps.log-validation.outcome == 'failure' || steps.metric-validation.outcome == 'failure') && !cancelled()
+        run: ./gradlew validator:run --args='-c eks/trace-validation.yml
+          --testing-id ${{ env.TESTING_ID }}
+          --endpoint http://${{ env.APP_ENDPOINT }}
+          --region ${{ env.AWS_DEFAULT_REGION }}
+          --account-id ${{ env.TEST_ACCOUNT }}
+          --metric-namespace ${{ env.METRIC_NAMESPACE }}
+          --log-group ${{ env.LOG_GROUP }}
+          --app-namespace ${{ env.SAMPLE_APP_NAMESPACE }}
+          --platform-info ${{ inputs.test-cluster-name }}
+          --service-name sample-application-${{ env.TESTING_ID }}
+          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_DEPLOYMENT_NAME }}
+          --request-body ip=${{ env.REMOTE_SERVICE_POD_IP }}
+          --rollup'
+
+       # Clean up Procedures
 
       - name: Remove log group deletion command
         if: always()
